### PR TITLE
Updated CSS

### PR DESCRIPTION
**Pull request by briansayre**
I updated the CSS to allow for a more modern feel and to make it easier on the eyes while looking at the current games. Let me know if there are any changes you would want me to make before you would consider merging, thanks!

P.S. huge fan of the project

### CODE REVIEW

**Comment by Merry3750** [comment]
This looks awesome! I just have 2 bits of feedback:
1) I think the live games need a bit of separation when not selected. Either a border or a background color.
2) The hue spectrums seem to have lost their centering.

I'm also not sure how I feel about the tilt shaking animation, but that's something I'll play around with in the future

**Comment by Merry3750** [comment]
Also, while I do think that it looks nicer with the video at the bottom of the page, having "What is Scorigami" be the last question in the FAQ feels wrong.

**Comment by briansayre** [comment]
I added more space + bottom border to the live games and fixed the spectrum centering. The video has been reverted but I added more spacing underneath to not feel so crammed. Open to any more feedback.

**Comment by Merry3750** [comment]
Just noticed that when you move the first game slider, the later scores are still white.

image

I also think the live games really need a complete border. They really bleed into each other without it.

**Comment by briansayre** [comment]
Added a separator between them so now it is much easier to tell the difference. The border can be expanded more too if you want. I also added a more "NFL" feel with a little NFL/origami logo, if you don't want it we can just remove the img tag no problem!

**Pull request merged**
